version: '3.8'

services:
  web:
    build: ../rosatom_fastapi
    volumes:
      - ../rosatom_fastapi:/usr/src/app/
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ml
      - POSTGRES_PASSWORD=ml_password
      - POSTGRES_DB=frames_db
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  postgres_data:
  minio-storage:
